export const bookEntries = [
	{ title: "Prologue: The First Light", pages: 5, type: "prologue" },
	{ title: "Stormblessed", pages: 28, type: "chapter" },
	{ title: "Honor is Dead", pages: 32, type: "chapter" },
	{ title: "The Blackthorn", pages: 25, type: "chapter" },
	{ title: "Logbook: Battle Report", pages: 4, type: "interlude" },
	{ title: "Letter from the King", pages: 3, type: "letter" },
	{ title: "The Shattered Plains", pages: 30, type: "chapter" },
	{ title: "The Tower", pages: 35, type: "chapter" },
	{ title: "Dream of Stormlight", pages: 5, type: "dream" },
	{ title: "The King's Wit", pages: 22, type: "chapter" },
	{ title: "Quote: Words of Radiance", pages: 1, type: "quote" },
	{ title: "Highstorm", pages: 26, type: "chapter" },
	{ title: "Bridge Four", pages: 31, type: "chapter" },
	{ title: "Map of the Shattered Plains", pages: 2, type: "map" },
	{ title: "Kaladin's Oath", pages: 29, type: "chapter" },
	{ title: "The Shardbearer", pages: 33, type: "chapter" },
	{ title: "Flashback: Gavilar's Last Words", pages: 3, type: "flashback" },
	{ title: "Dalinar's Vision", pages: 27, type: "chapter" },
	{ title: "Codex: Voidbinding", pages: 6, type: "codex" },
	{ title: "The Weeping", pages: 24, type: "chapter" },
	{ title: "The Parshendi", pages: 30, type: "chapter" },
	{ title: "Table of Contents", pages: 2, type: "table_of_contents" },
	{ title: "Vocabulary Guide", pages: 3, type: "vocabulary" },
	{ title: "The Assassin", pages: 28, type: "chapter" },
	{ title: "The Kholin Family", pages: 32, type: "chapter" },
	{ title: "Timeline: War of Reckoning", pages: 2, type: "timeline" },
	{ title: "Appendix A: Spren Types", pages: 4, type: "appendix" },
	{ title: "Epilogue: A New Oath", pages: 6, type: "epilogue" },
	{ title: "Poem: The Words Forgotten", pages: 1, type: "poem" },
	{ title: "Author's Note", pages: 2, type: "note" },
];
export type BookEntry = (typeof bookEntries)[number];
