export const DEFAULT_READER_INPUT_SETTINGS = {
	keyboardBaseStepPx: 32,
	keyboardDecayDelayMs: 280,
	keyboardDecayIntervalMs: 150,
	keyboardDecayStep: 0.2,
	keyboardDuration: 0.68,
	keyboardHoldBoost: 0.12,
	keyboardMaxMultiplier: 14,
	keyboardTapAccelerationPx: 50,
	keyboardTapBurstWindowMs: 320,
	keyboardTapMaxStepPx: 2500,
	keyboardTapRepeatMultiplier: 1.12,
	pageStepRatio: 0.88,
	middleDragAccelerationLimit: 5,
	middleDragDeltaRatio: 0.82,
	middleDragDuration: 0.14,
	middleDragVelocityRatio: 7,
	wheelAccelerationPx: 220,
	wheelBaseStepPx: 32,
	wheelBurstCountBoostPx: 32,
	wheelBurstCountLimit: 20,
	wheelBurstCountMagnitudeExponent: 1.45,
	wheelBurstCountMultiplier: 1.43,
	wheelBurstCountStepPx: 140,
	wheelBurstDecayMs: 650,
	wheelBurstEnergyLimit: 180000,
	wheelDeltaRatio: 0.7,
	wheelDuration: 0.75,
	wheelMaxStepPx: 1900,
	wheelResetDelayMs: 650,
	touchAccelerationLimit: 10,
	touchBurstDecayMs: 650,
	touchBurstEnergyLimit: 80000,
	touchBurstWindowMs: 650,
	touchDeltaRatio: 0.58,
	touchDuration: 0,
	touchMomentumDuration: 1.2,
	touchMomentumMaxPx: 2500,
	touchMomentumMinVelocity: 0.2,
	touchMomentumMultiplier: 390,
	touchVelocityRatio: 18,
};

export type ReaderInputSettings = typeof DEFAULT_READER_INPUT_SETTINGS;

export const NEW_READER_INPUT_SETTINGS = DEFAULT_READER_INPUT_SETTINGS;
