export const DEFAULT_READER_INPUT_SETTINGS = {
	keyboardBaseStepPx: 32,
	keyboardDecayDelayMs: 280,
	keyboardDecayIntervalMs: 150,
	keyboardDecayStep: 0.2,
	keyboardDuration: 0.68,
	keyboardHoldBoost: 0.08,
	keyboardMaxMultiplier: 12,
	keyboardTapAccelerationPx: 50,
	keyboardTapBurstWindowMs: 320,
	keyboardTapMaxStepPx: 1600,
	keyboardTapRepeatMultiplier: 1.08,
	pageStepRatio: 0.88,
	snapCapturePx: 96,
	snapDelayMs: 240,
	snapDuration: 0.22,
	middleDragAccelerationLimit: 5,
	middleDragDeltaRatio: 0.82,
	middleDragDuration: 0.14,
	middleDragVelocityRatio: 7,
	wheelAccelerationPx: 140,
	wheelBaseStepPx: 32,
	wheelBurstCountBoostPx: 0,
	wheelBurstCountLimit: 12,
	wheelBurstCountMultiplier: 1.18,
	wheelBurstDecayMs: 1350,
	wheelBurstEnergyLimit: 180000,
	wheelDeltaRatio: 0.68,
	wheelDuration: 0,
	wheelMaxStepPx: 1900,
	wheelResetDelayMs: 1350,
	touchAccelerationLimit: 3.2,
	touchBurstDecayMs: 950,
	touchBurstEnergyLimit: 80000,
	touchBurstWindowMs: 2200,
	touchDeltaRatio: 0.58,
	touchDuration: 0,
	touchMomentumDuration: 0.24,
	touchMomentumMaxPx: 1900,
	touchMomentumMinVelocity: 0.2,
	touchMomentumMultiplier: 390,
	touchVelocityRatio: 18,
};

export type ReaderInputSettings = typeof DEFAULT_READER_INPUT_SETTINGS;

export const NEW_READER_INPUT_SETTINGS = DEFAULT_READER_INPUT_SETTINGS;
