// server/db/seed.ts

import { db } from "../..";
import { tales } from "../../schema";
import { userId1, userId2 } from "../ids";

// You can call this in your main seed index file
export async function seedTales() {
  await db.insert(tales).values([
    {
      creatorId: userId1,
      bookId: 1,
      title: "Frostbound Legacy",
      slug: "public-tale1",
      description:
        "In the heart of winter, ancient powers stir beneath the ice.",
      isOfficial: false,
      editable: false,
      visibility: "public",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId2,
      bookId: 1,
      title: "Ashes of the Ember Crown",
      slug: "public-tale2",
      description: "Flames of rebellion rise as a forgotten kingdom awakens.",
      isOfficial: false,
      editable: true,
      visibility: "public",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId1,
      bookId: 1,
      title: "Secrets Beneath the Ice",
      slug: "private-tale1",
      description: "A silent world hides lost truths frozen in time.",
      isOfficial: false,
      editable: false,
      visibility: "private",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId2,
      bookId: 1,
      title: "Flames in the Shadows",
      slug: "private-tale2",
      description: "A fire burns quietly where no one dares to look.",
      isOfficial: false,
      editable: true,
      visibility: "private",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId1,
      bookId: 1,
      title: "The Ice Warden's Oath",
      slug: "restricted-tale1",
      description: "A lone guardian watches over the frozen veil of time.",
      isOfficial: false,
      editable: false,
      visibility: "restricted",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId1,
      bookId: 1,
      title: "Frozen Tides of Silence",
      slug: "restricted-tale2",
      description: "What was buried in snow may thaw into chaos.",
      isOfficial: false,
      editable: false,
      visibility: "restricted",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId2,
      bookId: 1,
      title: "Embers Behind the Gate",
      slug: "restricted-tale3",
      description: "When flame meets iron, secrets are forged in defiance.",
      isOfficial: false,
      editable: true,
      visibility: "restricted",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      creatorId: userId2,
      bookId: 1,
      title: "Cinderwake",
      slug: "restricted-tale4",
      description: "A spark that should’ve died now threatens the world anew.",
      isOfficial: false,
      editable: true,
      visibility: "restricted",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
    {
      bookId: 1,
      title: "Howl of Puppies",
      slug: "official-tale1",
      description: "Puppies howling in the wind.",
      isOfficial: true,
      editable: true,
      visibility: "public",
      status: "published",
      cloneable: "private",
      type: "hybrid",
    },
  ]);

  console.log("✅ Tales seeded!");
}
