CREATE TABLE "talescape_author" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_author_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fullName" text,
	"firstName" text,
	"lastName" text,
	"biography" text,
	"imageUrl" text
);
--> statement-breakpoint
CREATE TABLE "talescape_book" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_book_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"authorId" integer,
	"description" text,
	"coverImageUrl" text,
	"type" text DEFAULT 'user' NOT NULL,
	"userId" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_block_embed" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_block_embed_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blockId" integer NOT NULL,
	"taleId" integer NOT NULL,
	"sectionId" integer NOT NULL,
	"pageId" integer,
	"index" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_block_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_block_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blockId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_block" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creatorId" text,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"embeddable" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_fragment_embed" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_fragment_embed_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fragmentId" integer NOT NULL,
	"taleId" integer NOT NULL,
	"blockId" integer NOT NULL,
	"index" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_fragment_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_fragment_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fragmentId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_fragment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_fragment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creatorId" text,
	"type" text NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"embeddable" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"data" json NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_section_embed" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_section_embed_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sectionId" integer NOT NULL,
	"taleId" integer NOT NULL,
	"index" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_section_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_section_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sectionId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_section" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_section_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creatorId" text,
	"layout" text NOT NULL,
	"orientation" text NOT NULL,
	"inputMode" text[] NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"embeddable" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"partId" integer NOT NULL,
	"title" text NOT NULL,
	"type" text NOT NULL,
	"index" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_entry_range" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_entry_range_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"entryId" integer NOT NULL,
	"firstBlockId" integer NOT NULL,
	"lastBlockId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_page" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_page_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"partId" integer NOT NULL,
	"entryId" integer NOT NULL,
	"type" text NOT NULL,
	"isPaginated" boolean NOT NULL,
	"index" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_part_range" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_part_range_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"partId" integer NOT NULL,
	"firstBlockId" integer NOT NULL,
	"lastBlockId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_part" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_part_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"title" text NOT NULL,
	"index" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_tale_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_tale_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer,
	"userId" text,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_tale" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_tale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creatorId" text,
	"bookId" integer,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"description" text NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'public' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"type" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"url" varchar(1024) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_user" (
	"id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"firstName" text NOT NULL,
	"lastName" text NOT NULL,
	"fullName" text NOT NULL,
	"primaryEmailId" text,
	"emailVerifiedAt" timestamp with time zone,
	"imageUrl" text,
	CONSTRAINT "talescape_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "talescape_userEmail" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"email" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "talescape_book" ADD CONSTRAINT "talescape_book_authorId_talescape_author_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."talescape_author"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD CONSTRAINT "talescape_book_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_embed" ADD CONSTRAINT "talescape_block_embed_blockId_talescape_block_id_fk" FOREIGN KEY ("blockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_embed" ADD CONSTRAINT "talescape_block_embed_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_embed" ADD CONSTRAINT "talescape_block_embed_sectionId_talescape_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."talescape_section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_embed" ADD CONSTRAINT "talescape_block_embed_pageId_talescape_page_id_fk" FOREIGN KEY ("pageId") REFERENCES "public"."talescape_page"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_permission" ADD CONSTRAINT "talescape_block_permission_blockId_talescape_block_id_fk" FOREIGN KEY ("blockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_permission" ADD CONSTRAINT "talescape_block_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_embed" ADD CONSTRAINT "talescape_fragment_embed_fragmentId_talescape_fragment_id_fk" FOREIGN KEY ("fragmentId") REFERENCES "public"."talescape_fragment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_embed" ADD CONSTRAINT "talescape_fragment_embed_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_embed" ADD CONSTRAINT "talescape_fragment_embed_blockId_talescape_block_id_fk" FOREIGN KEY ("blockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_permission" ADD CONSTRAINT "talescape_fragment_permission_fragmentId_talescape_fragment_id_fk" FOREIGN KEY ("fragmentId") REFERENCES "public"."talescape_fragment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_permission" ADD CONSTRAINT "talescape_fragment_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ADD CONSTRAINT "talescape_fragment_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_section_embed" ADD CONSTRAINT "talescape_section_embed_sectionId_talescape_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."talescape_section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_section_embed" ADD CONSTRAINT "talescape_section_embed_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_section_permission" ADD CONSTRAINT "talescape_section_permission_sectionId_talescape_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."talescape_section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_section_permission" ADD CONSTRAINT "talescape_section_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_section" ADD CONSTRAINT "talescape_section_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry" ADD CONSTRAINT "talescape_entry_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry" ADD CONSTRAINT "talescape_entry_partId_talescape_part_id_fk" FOREIGN KEY ("partId") REFERENCES "public"."talescape_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry_range" ADD CONSTRAINT "talescape_entry_range_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry_range" ADD CONSTRAINT "talescape_entry_range_entryId_talescape_entry_id_fk" FOREIGN KEY ("entryId") REFERENCES "public"."talescape_entry"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry_range" ADD CONSTRAINT "talescape_entry_range_firstBlockId_talescape_block_id_fk" FOREIGN KEY ("firstBlockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry_range" ADD CONSTRAINT "talescape_entry_range_lastBlockId_talescape_block_id_fk" FOREIGN KEY ("lastBlockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_page" ADD CONSTRAINT "talescape_page_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_page" ADD CONSTRAINT "talescape_page_partId_talescape_part_id_fk" FOREIGN KEY ("partId") REFERENCES "public"."talescape_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_page" ADD CONSTRAINT "talescape_page_entryId_talescape_entry_id_fk" FOREIGN KEY ("entryId") REFERENCES "public"."talescape_entry"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_part_range" ADD CONSTRAINT "talescape_part_range_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_part_range" ADD CONSTRAINT "talescape_part_range_partId_talescape_part_id_fk" FOREIGN KEY ("partId") REFERENCES "public"."talescape_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_part_range" ADD CONSTRAINT "talescape_part_range_firstBlockId_talescape_block_id_fk" FOREIGN KEY ("firstBlockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_part_range" ADD CONSTRAINT "talescape_part_range_lastBlockId_talescape_block_id_fk" FOREIGN KEY ("lastBlockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_part" ADD CONSTRAINT "talescape_part_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_permission" ADD CONSTRAINT "talescape_tale_permission_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_permission" ADD CONSTRAINT "talescape_tale_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale" ADD CONSTRAINT "talescape_tale_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale" ADD CONSTRAINT "talescape_tale_bookId_talescape_book_id_fk" FOREIGN KEY ("bookId") REFERENCES "public"."talescape_book"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_image" ADD CONSTRAINT "talescape_image_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "talescape_image" USING btree ("name");