CREATE TABLE "talescape_author" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_author_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creatorId" text NOT NULL,
	"fullName" text,
	"firstName" text,
	"lastName" text,
	"biography" text,
	"imageId" integer,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_book" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_book_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"authorId" integer,
	"description" text,
	"coverImageId" integer,
	"type" text DEFAULT 'user' NOT NULL,
	"creatorId" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_author_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_author_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"authorId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_book_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_book_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bookId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_block" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"branchId" integer NOT NULL,
	"creatorId" text NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"pageId" integer NOT NULL,
	"entryId" integer NOT NULL,
	"partId" integer NOT NULL,
	"title" text,
	"description" text,
	"isChoiceBlock" boolean DEFAULT false NOT NULL,
	"isSnap" boolean DEFAULT false NOT NULL,
	"order" integer NOT NULL,
	"pageOrder" integer DEFAULT 0 NOT NULL,
	"sizeMode" text DEFAULT 'contentResponsive' NOT NULL,
	"sizeConfig" json DEFAULT '{}'::json NOT NULL,
	"readingConfig" json DEFAULT '{"animationConfig":{"entering":{"tracks":[]},"leaving":{"tracks":[]},"scrolling":{"tracks":[]}},"readingLength":null,"readingLengthMode":"content"}'::json NOT NULL,
	"transitionConfig" json DEFAULT '{"animationConfig":{"entering":{"tracks":[]},"leaving":{"tracks":[]}},"enteringLength":700,"flow":{"direction":"down","type":"linear"},"leavingLength":700}'::json NOT NULL,
	"styleConfig" json,
	"visibility" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_branch" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_branch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"creatorId" text NOT NULL,
	"parentBranchId" integer,
	"name" text NOT NULL,
	"title" text,
	"description" text,
	"order" integer NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_node" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_node_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"blockId" integer NOT NULL,
	"creatorId" text NOT NULL,
	"parentNodeId" integer,
	"stableId" text NOT NULL,
	"name" text,
	"isRoot" boolean DEFAULT false NOT NULL,
	"order" integer NOT NULL,
	"config" json NOT NULL,
	"styleConfig" json,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_fragment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_fragment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"blockId" integer NOT NULL,
	"nodeId" integer,
	"creatorId" text NOT NULL,
	"type" text NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"order" integer NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"data" json NOT NULL,
	"content" json DEFAULT '{"content":""}'::json NOT NULL,
	"placementConfig" json DEFAULT '{"mode":"normal"}'::json NOT NULL,
	"styleConfig" json,
	"visibleRange" json,
	"scrollAnimationPlayback" text DEFAULT 'scrub' NOT NULL,
	"animationConfig" json DEFAULT '{"entering":{"tracks":[]},"leaving":{"tracks":[]},"scrolling":{"tracks":[]}}'::json NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_path" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_path_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"fromBranchId" integer NOT NULL,
	"fromBlockId" integer,
	"toBranchId" integer NOT NULL,
	"toBlockId" integer,
	"creatorId" text NOT NULL,
	"type" text NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"label" text,
	"description" text,
	"order" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"partId" integer NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"type" text NOT NULL,
	"isNumbered" boolean DEFAULT false NOT NULL,
	"order" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_page" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_page_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"partId" integer NOT NULL,
	"entryId" integer NOT NULL,
	"title" text,
	"description" text,
	"type" text NOT NULL,
	"isPaginated" boolean NOT NULL,
	"order" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_part" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_part_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"order" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_block_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_block_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blockId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_branch_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_branch_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branchId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_fragment_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_fragment_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fragmentId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_path_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_path_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pathId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_tale_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_tale_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taleId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_official_animation_preset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_official_animation_preset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"target" text NOT NULL,
	"tracks" json NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_official_style_preset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_official_style_preset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"target" text NOT NULL,
	"styleConfig" json NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_official_transition_preset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_official_transition_preset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"flowConfig" json NOT NULL,
	"enteringAnimationPresetIds" integer[] DEFAULT '{}' NOT NULL,
	"leavingAnimationPresetIds" integer[] DEFAULT '{}' NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_official_visibility_preset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_official_visibility_preset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"range" json NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_tale_progress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_tale_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"taleId" integer NOT NULL,
	"seenBlockIds" integer[] DEFAULT '{}' NOT NULL,
	"seenPageIds" integer[] DEFAULT '{}' NOT NULL,
	"seenEntryIds" integer[] DEFAULT '{}' NOT NULL,
	"seenPartIds" integer[] DEFAULT '{}' NOT NULL,
	"lastBlockId" integer,
	"lastBlockInnerProgress" numeric(5, 4) DEFAULT '0' NOT NULL,
	"maxBlockIdReached" integer,
	"activePathIds" integer[] DEFAULT '{}' NOT NULL,
	"selectedBranchIds" integer[] DEFAULT '{}' NOT NULL,
	"seenPathIds" integer[] DEFAULT '{}' NOT NULL,
	"committedFragmentIds" integer[] DEFAULT '{}' NOT NULL,
	"seenBlockProgress" numeric(5, 4) DEFAULT '0' NOT NULL,
	"maxReadProgress" numeric(5, 4) DEFAULT '0' NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "talescape_tale" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_tale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creatorId" text NOT NULL,
	"bookId" integer,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"description" text NOT NULL,
	"isOfficial" boolean DEFAULT false NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"editable" boolean DEFAULT true NOT NULL,
	"visibility" text DEFAULT 'public' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"cloneable" text DEFAULT 'private' NOT NULL,
	"type" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"url" varchar(1024) NOT NULL,
	"userId" varchar(255),
	"isOfficial" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_userEmail" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"email" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "talescape_user" (
	"id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"firstName" text NOT NULL,
	"lastName" text NOT NULL,
	"fullName" text NOT NULL,
	"primaryEmailId" text,
	"emailVerifiedAt" timestamp with time zone,
	"imageUrl" text,
	"role" text DEFAULT 'member' NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	CONSTRAINT "talescape_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "talescape_author" ADD CONSTRAINT "talescape_author_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD CONSTRAINT "talescape_author_imageId_talescape_image_id_fk" FOREIGN KEY ("imageId") REFERENCES "public"."talescape_image"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD CONSTRAINT "talescape_book_authorId_talescape_author_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."talescape_author"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD CONSTRAINT "talescape_book_coverImageId_talescape_image_id_fk" FOREIGN KEY ("coverImageId") REFERENCES "public"."talescape_image"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD CONSTRAINT "talescape_book_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_author_permission" ADD CONSTRAINT "talescape_author_permission_authorId_talescape_author_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."talescape_author"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_author_permission" ADD CONSTRAINT "talescape_author_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book_permission" ADD CONSTRAINT "talescape_book_permission_bookId_talescape_book_id_fk" FOREIGN KEY ("bookId") REFERENCES "public"."talescape_book"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book_permission" ADD CONSTRAINT "talescape_book_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_branchId_talescape_branch_id_fk" FOREIGN KEY ("branchId") REFERENCES "public"."talescape_branch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_pageId_talescape_page_id_fk" FOREIGN KEY ("pageId") REFERENCES "public"."talescape_page"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_entryId_talescape_entry_id_fk" FOREIGN KEY ("entryId") REFERENCES "public"."talescape_entry"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD CONSTRAINT "talescape_block_partId_talescape_part_id_fk" FOREIGN KEY ("partId") REFERENCES "public"."talescape_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_branch" ADD CONSTRAINT "talescape_branch_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_branch" ADD CONSTRAINT "talescape_branch_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_node" ADD CONSTRAINT "talescape_node_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_node" ADD CONSTRAINT "talescape_node_blockId_talescape_block_id_fk" FOREIGN KEY ("blockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_node" ADD CONSTRAINT "talescape_node_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_node" ADD CONSTRAINT "talescape_node_parentNodeId_talescape_node_id_fk" FOREIGN KEY ("parentNodeId") REFERENCES "public"."talescape_node"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ADD CONSTRAINT "talescape_fragment_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ADD CONSTRAINT "talescape_fragment_blockId_talescape_block_id_fk" FOREIGN KEY ("blockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ADD CONSTRAINT "talescape_fragment_nodeId_talescape_node_id_fk" FOREIGN KEY ("nodeId") REFERENCES "public"."talescape_node"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ADD CONSTRAINT "talescape_fragment_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_fromBranchId_talescape_branch_id_fk" FOREIGN KEY ("fromBranchId") REFERENCES "public"."talescape_branch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_fromBlockId_talescape_block_id_fk" FOREIGN KEY ("fromBlockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_toBranchId_talescape_branch_id_fk" FOREIGN KEY ("toBranchId") REFERENCES "public"."talescape_branch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_toBlockId_talescape_block_id_fk" FOREIGN KEY ("toBlockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry" ADD CONSTRAINT "talescape_entry_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_entry" ADD CONSTRAINT "talescape_entry_partId_talescape_part_id_fk" FOREIGN KEY ("partId") REFERENCES "public"."talescape_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_page" ADD CONSTRAINT "talescape_page_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_page" ADD CONSTRAINT "talescape_page_partId_talescape_part_id_fk" FOREIGN KEY ("partId") REFERENCES "public"."talescape_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_page" ADD CONSTRAINT "talescape_page_entryId_talescape_entry_id_fk" FOREIGN KEY ("entryId") REFERENCES "public"."talescape_entry"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_part" ADD CONSTRAINT "talescape_part_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_permission" ADD CONSTRAINT "talescape_block_permission_blockId_talescape_block_id_fk" FOREIGN KEY ("blockId") REFERENCES "public"."talescape_block"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_block_permission" ADD CONSTRAINT "talescape_block_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_branch_permission" ADD CONSTRAINT "talescape_branch_permission_branchId_talescape_branch_id_fk" FOREIGN KEY ("branchId") REFERENCES "public"."talescape_branch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_branch_permission" ADD CONSTRAINT "talescape_branch_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_permission" ADD CONSTRAINT "talescape_fragment_permission_fragmentId_talescape_fragment_id_fk" FOREIGN KEY ("fragmentId") REFERENCES "public"."talescape_fragment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_fragment_permission" ADD CONSTRAINT "talescape_fragment_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path_permission" ADD CONSTRAINT "talescape_path_permission_pathId_talescape_path_id_fk" FOREIGN KEY ("pathId") REFERENCES "public"."talescape_path"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path_permission" ADD CONSTRAINT "talescape_path_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_permission" ADD CONSTRAINT "talescape_tale_permission_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_permission" ADD CONSTRAINT "talescape_tale_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_progress" ADD CONSTRAINT "talescape_tale_progress_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_progress" ADD CONSTRAINT "talescape_tale_progress_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale" ADD CONSTRAINT "talescape_tale_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale" ADD CONSTRAINT "talescape_tale_bookId_talescape_book_id_fk" FOREIGN KEY ("bookId") REFERENCES "public"."talescape_book"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_image" ADD CONSTRAINT "talescape_image_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "talescape_image" USING btree ("name");