CREATE TABLE "talescape_tale_progress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_tale_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"taleId" integer NOT NULL,
	"seenBlockIds" integer[] DEFAULT '{}' NOT NULL,
	"lastBlockId" integer,
	"maxBlockIdReached" integer,
	"seenBlockProgress" numeric(5, 4) DEFAULT '0' NOT NULL,
	"linearReadProgress" numeric(5, 4) DEFAULT '0' NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "talescape_tale_progress" ADD CONSTRAINT "talescape_tale_progress_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_tale_progress" ADD CONSTRAINT "talescape_tale_progress_taleId_talescape_tale_id_fk" FOREIGN KEY ("taleId") REFERENCES "public"."talescape_tale"("id") ON DELETE no action ON UPDATE no action;