CREATE TABLE "talescape_author_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_author_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"authorId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talescape_book_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talescape_book_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bookId" integer NOT NULL,
	"userId" text NOT NULL,
	"permissionTypes" text[] NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "talescape_book" RENAME COLUMN "userId" TO "creatorId";--> statement-breakpoint
ALTER TABLE "talescape_book" DROP CONSTRAINT "talescape_book_userId_talescape_user_id_fk";
--> statement-breakpoint
ALTER TABLE "talescape_block" ALTER COLUMN "creatorId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_branch" ALTER COLUMN "creatorId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ALTER COLUMN "creatorId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_section" ALTER COLUMN "creatorId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_tale" ALTER COLUMN "creatorId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD COLUMN "creatorId" text NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD COLUMN "isOfficial" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD COLUMN "editable" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD COLUMN "visibility" text DEFAULT 'private' NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD COLUMN "isOfficial" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD COLUMN "editable" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD COLUMN "visibility" text DEFAULT 'private' NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_block" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_branch" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_fragment" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD COLUMN "creatorId" text NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_section" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_tale" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_user" ADD COLUMN "role" text DEFAULT 'member' NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_user" ADD COLUMN "isVerified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "talescape_author_permission" ADD CONSTRAINT "talescape_author_permission_authorId_talescape_author_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."talescape_author"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_author_permission" ADD CONSTRAINT "talescape_author_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book_permission" ADD CONSTRAINT "talescape_book_permission_bookId_talescape_book_id_fk" FOREIGN KEY ("bookId") REFERENCES "public"."talescape_book"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book_permission" ADD CONSTRAINT "talescape_book_permission_userId_talescape_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_author" ADD CONSTRAINT "talescape_author_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_book" ADD CONSTRAINT "talescape_book_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talescape_path" ADD CONSTRAINT "talescape_path_creatorId_talescape_user_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."talescape_user"("id") ON DELETE no action ON UPDATE no action;