import type { ReactNode } from "react";
import type { EntryType } from "~/lib/data";
import {
	ChevronUp,
	ChevronDown,
	QuoteIcon,
	MailIcon,
	DramaIcon,
	MapIcon,
	TableOfContentsIcon,
	BookAIcon,
	ScrollTextIcon,
	PaperclipIcon,
	BrainIcon,
	BookMarkedIcon,
	HourglassIcon,
	ListEndIcon,
	ListStartIcon,
	MoonStarIcon,
	NotepadTextIcon,
	CircleHelpIcon,
	BookOpenIcon,
} from "lucide-react";

export const ICON_MAP: Record<EntryType, ReactNode> = {
	cover: <BookOpenIcon className="inline" />,
	chapter: null,
	prologue: <ListStartIcon className="inline" />,
	epilogue: <ListEndIcon className="inline" />,
	timeline: <HourglassIcon className="inline" />,
	codex: <BookMarkedIcon className="inline" />,
	flashback: <BrainIcon className="inline" />,
	quote: <QuoteIcon className="inline" />,
	dream: <MoonStarIcon className="inline" />,
	letter: <MailIcon className="inline" />,
	interlude: <DramaIcon className="inline" />,
	map: <MapIcon className="inline" />,
	table_of_contents: <TableOfContentsIcon className="inline" />,
	vocabulary: <BookAIcon className="inline" />,
	appendix: <PaperclipIcon className="inline" />,
	poem: <ScrollTextIcon className="inline" />,
	note: <NotepadTextIcon className="inline" />,
	unknown: <CircleHelpIcon className="inline" />,
};
