export const NEW_READER_INPUT_SETTINGS = {
	keyboardBaseStepPx: 30,
	keyboardDecayDelayMs: 280,
	keyboardDecayIntervalMs: 150,
	keyboardDecayStep: 0.2,
	keyboardDuration: 0.18,
	keyboardHoldBoost: 0.025,
	keyboardMaxMultiplier: 4,
	keyboardTapAccelerationPx: 22,
	keyboardTapBurstWindowMs: 520,
	keyboardTapMaxStepPx: 620,
	keyboardTapRepeatMultiplier: 1.12,
	pageStepRatio: 0.82,
	snapCapturePx: 96,
	snapDelayMs: 240,
	snapDuration: 0.22,
	wheelAccelerationPx: 11,
	wheelBaseStepPx: 16,
	wheelDeltaRatio: 0.42,
	wheelDuration: 0.18,
	wheelMaxStepPx: 620,
	wheelRepeatMultiplier: 1.045,
	wheelResetDelayMs: 340,
};
