export const NEW_READER_INPUT_SETTINGS = {
	keyboardBaseStepPx: 42,
	keyboardDecayDelayMs: 240,
	keyboardDecayIntervalMs: 150,
	keyboardDecayStep: 0.25,
	keyboardDuration: 0.16,
	keyboardHoldBoost: 0.02,
	keyboardMaxMultiplier: 3,
	keyboardTapAccelerationPx: 32,
	keyboardTapBurstWindowMs: 480,
	keyboardTapMaxStepPx: 680,
	keyboardTapRepeatMultiplier: 1.16,
	pageStepRatio: 0.82,
	snapCapturePx: 96,
	snapDelayMs: 240,
	snapDuration: 0.22,
	wheelAccelerationPx: 13,
	wheelBaseStepPx: 24,
	wheelDeltaRatio: 0.5,
	wheelDuration: 0.15,
	wheelMaxStepPx: 350,
	wheelRepeatMultiplier: 1.03,
	wheelResetDelayMs: 240,
};
