"use client";

export type ReaderInputBindingSettings = {
	desktopDragBaseMultiplier: number;
	desktopDragFreeGestureCount: number;
	desktopDragFreeScrollEnabled: boolean;
	desktopDragRepeatMultiplier: number;
	desktopDragStopSnapDelayMs: number;
	desktopDragWindowMs: number;
	touchDragBaseMultiplier: number;
	touchDragFreeScrollEnabled: boolean;
	touchDragFreeGestureCount: number;
	touchDragHorizontalMultiplier: number;
	touchDragRepeatMultiplier: number;
	touchDragStopSnapDelayMs: number;
	touchDragWindowMs: number;
	keyboardAccelerationPx: number;
	keyboardBaseStepPx: number;
	keyboardBurstFreeScrollCount: number;
	keyboardBurstWindowMs: number;
	keyboardDuration: number;
	keyboardEase: gsap.EaseString;
	keyboardFreeScrollEnabled: boolean;
	keyboardHoldIntervalMs: number;
	keyboardMaxStepPx: number;
	keyboardRepeatMultiplier: number;
	keyboardStopSnapDelayMs: number;
	releaseThreshold: number;
	snapDuration: number;
	snapEase: gsap.EaseString;
	wheelAccelerationPx: number;
	wheelBaseStepPx: number;
	wheelDuration: number;
	wheelEase: gsap.EaseString;
	wheelFreeScrollEventCount: number;
	wheelFreeScrollEnabled: boolean;
	wheelMaxStepPx: number;
	wheelRepeatMultiplier: number;
	wheelStopSnapDelayMs: number;
};

export const READER_INPUT_BINDING_SETTINGS: ReaderInputBindingSettings = {
	snapDuration: 0.38,
	snapEase: "power2.out",
	releaseThreshold: 24,
	desktopDragBaseMultiplier: 3,
	desktopDragFreeGestureCount: 1,
	desktopDragFreeScrollEnabled: false,
	desktopDragRepeatMultiplier: 1.35,
	desktopDragStopSnapDelayMs: 180,
	desktopDragWindowMs: 650,
	touchDragBaseMultiplier: 1.6,
	touchDragFreeScrollEnabled: false,
	touchDragFreeGestureCount: 1,
	touchDragHorizontalMultiplier: 1.9,
	touchDragRepeatMultiplier: 1.25,
	touchDragStopSnapDelayMs: 2000,
	touchDragWindowMs: 800,
	keyboardBaseStepPx: 7,
	keyboardBurstFreeScrollCount: 3,
	keyboardBurstWindowMs: 500,
	keyboardRepeatMultiplier: 2,
	keyboardStopSnapDelayMs: 150,
	keyboardFreeScrollEnabled: false,
	keyboardAccelerationPx: 80,
	keyboardMaxStepPx: 2400,
	keyboardHoldIntervalMs: 60,
	keyboardDuration: 0.38,
	keyboardEase: "power2.out",
	wheelStopSnapDelayMs: 500,
	wheelFreeScrollEventCount: 5,
	wheelFreeScrollEnabled: false,
	wheelBaseStepPx: 12,
	wheelAccelerationPx: 60,
	wheelRepeatMultiplier: 1.2,
	wheelMaxStepPx: 2400,
	wheelDuration: 0.38,
	wheelEase: "power2.out",
};
